# docker-based development environment
services:
  app:
    image: paypal-stock-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"

# attach volume, and enable watch- to rebuild container
    volumes:
      - .:/code:rw
      - ./stock.db:/stock.db
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml

  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: